services:
  - type: web
  name: blogapp-frontend
  env: static
  buildCommand: npm install && npm run build
  staticPublishPath: ./dist
  routes:
    - type: rewrite
    source: /*
    destination: /index.html
  headers:
    - source: /*
    headers:
      - key: Cache-Control
        value: no-store